# Generated by Django 5.2.16 on 2026-07-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_settlement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
